### ISSUE TITLE
script func_tweak_path ch16 error

### ISSUE THREAD

**Issue by Ferlinuxdebian** [vossenjp/bashcookbook-examples#1]
See the line:

```
# Make sure it's not already in the $PATH
if [ $(contains "$PATH" "$directory") ]; then
echo "$0:$FUNCNAME: '$directory' already in \$PATH--aborting" >&2
```

This warning message from the echo command:

```
echo "$0:$FUNCNAME: '$directory' already in \$PATH--aborting" >&2
```
It is never shown because when in the contains function the value is equal to an existing value the return code is "1" and the if statement above is dealing only with output code "0"

For shows I had to put the "!" of denial in the script, being:

```
 # Make sure it's not already in the $PATH
    if ! [ $(contains "$PATH" "$directory") ]; then
```
Sorry English, I'm Brazilian and I did what I could, thank you!

**Comment by vossenjp** [comment]
Wow, `ch16/func_tweak_path` was really broken, thanks for the report!

In addition to the problem you reported, I found some other problems and minor tweaks and made those too.

* [master b3cc839] BUGFIX for ch16/func_tweak_path to fix missing spaces before NoOps
* [master 44359a4] BUGFIX for ch16/func_tweak_path per Github bug #1, thanks to @Ferlinuxdebian
* [master d133344] Comment/usage bugfix for ch16/func_tweak_path clarity
* [master 1bf34ea] ch16/func_tweak_path add spaces for style consistency

**Comment by Ferlinuxdebian** [comment]
Yours is expecional book, it is a pleasure to be able to help.

**Comment by vossenjp** [comment]
We're very glad you like it, thanks for the feedback!
